#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 18 18:18:44 2022

@author: skciller
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn import datasets

#set seed variable for reproducibility
random_seed = 25
np.random.seed(random_seed)


